version: "2.2"
networks:
  appnetwork:
    driver: bridge
  gamenetwork:
    driver: bridge
services:
##Postgres
  postgres:
    container_name: postgresdb
    image: postgres:latest
    restart: always
    networks:
      - appnetwork
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ${FILEPLACE}/postgres/:/var/lib/postgresql/data
##Nextcloud
  nextcloud:
    depends_on:
     - postgres
    image: linuxserver/nextcloud
    container_name: nextcloud
    environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=${TZ}
    volumes:
        - ${FILEPLACE}/nextcloud/appdata/:/config
        - ${FILEPLACE}/nextcloud/data/:/data
    restart: unless-stopped
    networks:
      - appnetwork
##letsencrypt-Proxy
  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    cap_add:
        - NET_ADMIN
    environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=${TZ}
        - URL=${URL}
        - ONLY_SUBDOMAINS=false
        - VALIDATION=http
        - EMAIL=${EMAIL}
    volumes:
        - ${FILEPLACE}/letsencrypt/:/config
    ports:
        - 443:443
        - 80:80
    restart: unless-stopped
    networks:
      - appnetwork
##heimdall
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=${TZ}
    volumes:
        - ${FILEPLACE}/heimdall/:/config
    restart: unless-stopped
    networks:
      - appnetwork
##minecraft
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft
    environment:
        #- PUID=${PUID}
        #- PGID=${PGID}
        #- TZ=${TZ}
        - EULA=TRUE
    volumes:
        - ${FILEPLACE}/minecraft/:/data
    restart: unless-stopped
    networks:
      - gamenetwork
    ports:
      - 25565:25565